### ISSUE TITLE
Enable more than 2 input streams

### ISSUE THREAD

**Issue by cookieisland** [rocky4546/tvheadend-locast#11]
Would it be possible to use a second locast login/password for the same location so that we can get past the maximum of 2 input streams?  I was browsing locast2dvr (https://pypi.org/project/locast2dvr/) and it looks like it has a feature called  'multiplexing' that may do this....

Maybe a configuration such as the following with 2 usernames for the same city could be possible. The trick would be for tvheadend-locast to automatically switch to the 2nd instance when the 1st instance is fully used.

[locast_sfo1]
login-username = name1@gmail.com
login-password = xxxxxx
label = Locast SFO1
epg-suffix = L

[locast_sfo2]
login-username = name2@gmail.com
login-password = xxxxxx
label = Locast SFO2
epg-suffix = L

**Comment by rocky4546** [comment]
Already implemented as of today... not checked in. I posted that improvement on the forum site.  On top of that it needed to also use load balancing of the tuners and will spread them across the different instances.  There is not a limitation to the number of instances that can be used.  Obviously, you would need multiple account and using the same account would still only give you 4 tuners.  Once the instances are added, then update the number of tuners from 4 to 8 and it should run until all 8 are used.

**Comment by rocky4546** [comment]
Double checked and yes, you would need to increase the plugin tuner count to 8 to get all 8 streams running.  The total tuner-count is at the namespace level and the instance then tags or uses a tuner slot.  The system counts the number of tuners used per instance and allocates the next stream based on the least used instance.

**Comment by cookieisland** [comment]
Excellent! 

I assume this means that when this new feature rolls out I should also change the number of input streams from 2 to 4 in tvheadend right?

**Comment by rocky4546** [comment]
yes. The reason for 4 is only when tvheadend does a rescan at the Network level.  It runs on all tuners as fast as it can and takes up twice the tuners listed in tvheadend. If you are careful, it can be more, like 6, but you have to set the network scan to manual and when you scan, remember to change the tuners back to 4; otherwise, the account normally gets locked out. That is the reason the old locast2plex had it set to 3. Working hard on the channel editor.  May not have all functions done by COB, but trying to get as far as I can. Will release what I have tonight.

**Comment by rocky4546** [comment]
BTW, locast2dvr multiplexing really means using the 4 tuners within one process instead of using 4 tuners in 4 processes with 4 different web ports.  It is not really multiplexing. It still uses just one account with a max of 4 streams.

**Comment by cookieisland** [comment]
Ah yes, that makes sense. Their docs triggered me to think that multiple
logins could solve the max 2 input streams barrier I was hitting.  I have a
couple of active tvs and also like to record shows so I was getting into
trouble with the max 2 issue.

**Comment by cookieisland** [comment]
I will test your update asap but I am mostly busy tomorrow.......

**Comment by cookieisland** [comment]
I tried your updates just now and found a couple of issues:
1) only the first instances' password is encrypted. The password for the 2nd instance was not encrypted.
2) I am not sure how to change the tuner_count from 4 to 8. I tried a few ways and I don't think I suceeded based on messages and/or errors.

I started by setting it in each of the instances but I kept getting the following messages in the log for each instance.
```
2021-05-16 13:32:53,690-DEBUG:web_handler TunerHttpHandler Implementing 4 tuners for Locast
```

Here is what the relevant portions of my config.ini looked like:
```
[locast_sfo]
login-username = id1@gmail.com
login-password = ENC::xxxxxx
label = Locast SFO
m3u-group_hdtv = SFO-HDTV
m3u-group_sdtv = SFO-SDTV
epg-suffix = L
dma = 807
city = San Francisco
player-tuner_count = 8

[locast_sfo2]
login-username = id2@gmail.com
login-password = yyyyyy
label = Locast SFO2
m3u-group_hdtv = SFO-HDTV
m3u-group_sdtv = SFO-SDTV
epg-suffix = L
dma = 807
city = San Francisco
player-tuner_count = 8

[main]
use_encryption = True
uuid = xxxxxx

```

I also tried setting player-tuner_count in the [main] section but each instance still said it was implementing 4 tuners.  

I also tried setting it in [locast] section and then I got exceptions as follows:

```
2021-05-16 13:28:37,814-INFO:main Initiating Cabernet v0.8.4b
2021-05-16 13:28:37,816-INFO:main Getting Plugins...
2021-05-16 13:28:37,817-DEBUG:plugin_handler Plugin Defn file loaded
Traceback (most recent call last):
  File "/app/lib/plugins/plugin_handler.py", line 52, in collect_plugins
    importlib.resources.read_text(_plugins_pkg, folder)
  File "/usr/local/lib/python3.8/importlib/resources.py", line 169, in read_text
    with open_text(package, resource, encoding, errors) as fp:
  File "/usr/local/lib/python3.8/importlib/resources.py", line 125, in open_text
    return TextIOWrapper(reader.open_resource(resource), encoding, errors)
  File "<frozen importlib._bootstrap_external>", line 988, in open_resource
IsADirectoryError: [Errno 21] Is a directory: '/app/plugins/provider_video_locast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/tvh_main.py", line 11, in <module>
    main.main(script_dir)
  File "/app/lib/main.py", line 84, in main
    plugins = plugin_handler.PluginHandler(config_obj)
  File "/app/lib/plugins/plugin_handler.py", line 43, in __init__
    self.collect_plugins(self.config_obj.data['paths']['internal_plugins_pkg'])
  File "/app/lib/plugins/plugin_handler.py", line 55, in collect_plugins
    plugin = Plugin(self.config_obj, self.plugin_defn, '.'.join([_plugins_pkg, folder]))
  File "/app/lib/plugins/plugin.py", line 53, in __init__
    self.load_config_defn()
  File "/app/lib/plugins/plugin.py", line 74, in load_config_defn
    defn_obj.call_oninit(self.config_obj)
  File "/app/lib/config/config_defn.py", line 139, in call_oninit
    config_callbacks.call_function(settings['onInit'], section, key, _config_obj)
  File "/app/lib/config/config_callbacks.py", line 58, in call_function
    return func(_config_obj, _section, _key)
  File "/app/lib/config/config_callbacks.py", line 237, in check_value_4
    if not 1 <= value <= 4:
TypeError: '<=' not supported between instances of 'int' and 'str'
```

Can you tell me the proper way to set tuner count to 8?

Thanks!

**Comment by rocky4546** [comment]
Thanks for the test results.  My desktop computer OS drive died last night. I love Clonezilla!  Best product ever.  Plugged in another drive and restored from backup.  I'm back, but need to run a number of upgrades.  Will probably take a few hours, but will get on it.

**Comment by rocky4546** [comment]
All items have been addressed. To increase tuner count, the Client > Concurrent Listeners must be high enough to support all plugins.  So at least 8.  Then increasing the tuner count for the plugin will work.  At some point, I suppose I could count the tuners per plugin and use that, but for now, I allow the user to set the concurrent listeners.

**Comment by rocky4546** [comment]
All items have been addressed. To increase tuner count, the Client > Concurrent Listeners must be high enough to support all plugins.  So at least 8.  Then increasing the tuner count for the plugin will work.  At some point, I suppose I could count the tuners per plugin and use that, but for now, I allow the user to set the concurrent listeners.

**Comment by rocky4546** [comment]
Decided to add a couple of items to help.
- tuner listeners are now calculated based on the total tuners requested across all plugins.  So concurrent listeners are only associated with the webadmin site.
- if you turn on use_encryption from the website, it will check to see if cryptography is installed.  If not, it will send a message back to page stating it cannot encrypt passwords until module is installed. (it will still check the box, but it won't do anything).

**Comment by cookieisland** [comment]
Thanks! Due to commitments I will not be able to test for a few days but
will get to it as soon as I can.

**Comment by cookieisland** [comment]
Tested it. Looking good now. Thanks!

**Comment by rocky4546** [comment]
0.8.4j is a stable release and includes the fix.  Closing issue.
