### ISSUE TITLE
[Feature Request] Multiplexing & Remapping for muliple zip codes

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [rocky4546/tvheadend-locast#13]
https://wouterdebie.github.io/locast2tuner/advanced/multiplexing.html
https://wouterdebie.github.io/locast2tuner/advanced/remapping.html

This would combine multiple digital tuners in a single server into one url and remap the channel numbers. So instead of running 2-3 tvheadend locast we can only run one.

**Comment by rocky4546** [comment]
Just a note.  We do not use multiplexing and remapping like locast2tuner; instead, we have the ability to use multiple instances of a single plugin.  this is accomplished with the config.ini.  You may have realized this, but each instance of a locast plugin has the ability to provide an additional 4 tuners (using a separate account) which is multiplexed using a round-robin approach. This would allow multiple zipcodes to be used (one per instance.) 

For remapping, we have multiple ways to handle this.  One is to directly remap any channel in the channel editor.  Second is to set config parameters to change all channels for an instance (such as add 100 to the channel number).

I figure you saw some of the abilities in the web portal, but wanted to add this in case someone was looking up the answer.  Many of these thoughts can be found in the forum https://tvheadend.org/boards/5/topics/43052

Finally, the requests for channels and EPG data is available at the app, plugin and instance levels.  As an example
http://ipaddress:6077/channels.m3u
http://ipaddress:6077/Locast/channels.m3u
http://ipaddress:6077/Locast/default/channels.m3u
Each request will give the integrated result desired.
